version: "3.7"

services:
  flaskapp:
    build:
      context: ./
    depends_on:
      - db
    ports:
      - 5000:5000
  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro